import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "How to Raise Over $10M In Crowdfunding",
    subTitle:
      "Startup Survivor & Drone Pioneer, Thomas Agaraté Will Teach You the 'Copy-and-Paste' for Crowdfunding Success a $1 Million Dollar Success",
    description:
      "Customers are buying online more than ever and crowdfunding is at its peak. Don't wait! This detailed course explains startup survivor and drone pioneer, Thomas Agaraté's winning method from A to Z. It actually took him 5 years to learn and discover all the skills shown in this course, so whatever your marketing skills, you’ll get tons of value. You'll learn a tested and proven formula. Thomas' method has been used over and over again, with consistent awesome results. Campaigners who used this method raised 5 to 20x more. So if you wanna be one of them, this is the right place for you. Get simple tools and processes you can follow and execute like a professional.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Business/crowdfunding.jpg?raw=true",
    originalPrice: "4999",
    discountedPrice: "1899",
    discount: "62",
    createdBy: "Crowdfunding Value Bomb",
    language: ["English"],
    duration: "2h 10m",
    noOfLectures: "23",
    rating: "4.5",
    categoryName: "Business",
  },
  {
    _id: uuid(),
    title: "Business Analysis: Working with Use Cases",
    subTitle:
      "An introductory course on use case modeling for Business Analysts or those looking to transition into a BA role.",
    description:
      "Use cases are one of the most commonly used techniques for analyzing and modeling systems and business processes.  They are a core component of every Business Analyst's toolbox. This course will give you everything you need to know to get up and running with this powerful methodology of analysis. The course consists of four lectures plus a case study.  It should take no longer than two hours to complete. Students will be able to download a use case template for their own personal or business use.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Business/business%20analysis.jpg?raw=true",
    originalPrice: "3499",
    discountedPrice: "455",
    discount: "87",
    createdBy: "Don Hussey",
    language: ["English", "French"],
    duration: "2h 5m",
    noOfLectures: "22",
    rating: "4.0",
    categoryName: "Business",
  },
  {
    _id: uuid(),
    title: "How To Write A Business Plan And A Winning Business Model",
    subTitle:
      "Business plan template & business plan examples: Create a top business model & business plan for your business ideas",
    description:
      "Revolutionary, new way to write a professional business plan that will help you identify the most effective business strategies for your situation. Take this step to start your business, achieve independence, and become your own boss. Latest course update for 2022",
    img: "https://raw.githubusercontent.com/pankaj-prog/Ecom-images/main/Business/business-plan.webp",
    originalPrice: "3200",
    discountedPrice: "455",
    discount: "86",
    createdBy: "ALex Genadinik",
    language: ["English", "French", "German"],
    duration: "6h 49m",
    noOfLectures: "93",
    rating: "4.2",
    categoryName: "Business",
  },
  {
    _id: uuid(),
    title: "Entrepreneurship Academy: Strategize & Start A Business",
    subTitle:
      "Complete Bootcamp To Start A Business: Business Strategy, Marketing, Sales, Business Planning, Leadership, Growth",
    description:
      "Business school teaches you how to work for others, but this course will teach you how to work for yourself.You can build your own business, or be hired to build the business of your boss.Investing in a business can 10X your income in just a few years.",
    img: "https://raw.githubusercontent.com/pankaj-prog/Ecom-images/main/Business/entrepreneurship.webp",
    originalPrice: "12800",
    discountedPrice: "4480",
    discount: "65",
    createdBy: "Orlando Rene Chavez",
    language: ["English", "German"],
    duration: "11h 34m",
    noOfLectures: "100",
    rating: "3.5",
    categoryName: "Business",
  },
  {
    _id: uuid(),
    title: "The Complete Introduction To Accounting and Finance",
    subTitle:
      "The Original Course on Accounting & Finance! It's easy once you know the basics. Learn introductory accounting & finance.",
    description:
      "This course teaches entrepreneurs, startups and small businesses all things business accounting and entrepreneurial finance related, A to Z.  Starting with an introduction to accounting concepts, we move into financial reports and how to create them, understand them and analyze them.  Bookkeepers, Accountants, CFO's and Business Owners alike would all benefit from this course. Next, we learn about budgeting and forecasting.  Next we discuss growing your company, how to understand and analyze it using non conventional reports. After growing your company, we talk about raising capital and what is involved and avenues you can take.  One section is devoted to the initial public offering process and the timing, costs and best business practices involved. Last, we discuss exit strategies and how to give your investors and yourself a payoff for your hard work. This course is truly a start to finish of accounting and finance. At over 12 hours long, I wanted to make sure you will feel empowered and educated after taking the course. ",
    img: "https://raw.githubusercontent.com/pankaj-prog/Ecom-images/main/Business/accounting%20and%20finance.jpg",
    originalPrice: "3499",
    discountedPrice: "455",
    discount: "87",
    createdBy: "Chris Benjamin",
    language: ["English", "French", "German", "Italian"],
    duration: "8h 37m",
    noOfLectures: "79",
    rating: "3.8",
    categoryName: "Business",
  },
  {
    _id: uuid(),
    title: "Complete Blender Creator: Learn 3D Modelling for Beginners",
    subTitle:
      "Use Blender to Create Beautiful 3D models for Video Games, 3D Printing & More. Beginners Level Course",
    description:
      "Blender is a fantastic platform which enables you to make AAA-quality models which can be exported to any game engine, 3D printer, or other software.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Design/Blender%20creator.jpg?raw=true",
    originalPrice: "3499",
    discountedPrice: "455",
    discount: "87",
    createdBy: "GameDev.tv Team, Rick Davidson",
    language: ["English", "French"],
    duration: "36h 36m",
    noOfLectures: "243",
    rating: "4.5",
    categoryName: "Design",
  },
  {
    _id: uuid(),
    title: "The Ultimate Drawing Course - Beginner to Advanced",
    subTitle:
      "Learn the #1 most important building block of all art, Drawing. This course will teach you how to draw like a pro!",
    description:
      "Join over 450,000 learning student and start gaining the drawing skills you've always wanted. The Ultimate Drawing Course will show you how to create advanced art that will stand up as professional work. This course will enhance or give you skills in the world of drawing - or your money back. The course is your track to obtaining drawing skills like you always knew you should have! Whether for your own projects or to draw for other people. This course will take you from having little knowledge in drawing to creating advanced art and having a deep understanding of drawing fundamentals.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Design/Drawing%20course.jpeg?raw=true",
    originalPrice: "7500",
    discountedPrice: "2625",
    discount: "65",
    createdBy: "Jaysen Batchelor",
    language: ["English", "French", "German"],
    duration: "11h 8m",
    noOfLectures: "64",
    rating: "3.0",
    categoryName: "Design",
  },
  {
    _id: uuid(),
    title: "Photoshop Beginners Mastery: Zero to Hero in Photoshop",
    subTitle:
      "Learn Photoshop quickly and easily with essentials of Adobe Photoshop to produce beautiful images in Adobe Photoshop.",
    description:
      "This introductory course to Photoshop covers the fundamental functions to get started editing and improving photos. The student learns how to customize workspaces and panels, navigate the canvas effectively, work with multiple images and file types, and use various methods of image enhancement, including layering, selecting, and masking. Support files are included for this course, so students can follow along in the hands-on lectures. If you're a beginner to Photoshop or simply want to learn more about various selections, layering, and masking techniques, this course is for you!",
    img: "https://raw.githubusercontent.com/pankaj-prog/Ecom-images/main/Design/Photoshop.avif",
    originalPrice: "2999",
    discountedPrice: "1649",
    discount: "45",
    createdBy: "Chad Neuman",
    language: ["English"],
    duration: "3h 3m",
    noOfLectures: "46",
    rating: "2.5",
    categoryName: "Design",
  },
  {
    _id: uuid(),
    title: "Design Thinking in 3 Steps",
    subTitle:
      "Understand your audience, envision a creative solution, and test your prototype",
    description:
      "In this course, you’ll learn design thinking from the people who helped invent it. Designit is a global strategic design firm, and our designers help organizations across the globe learn and adopt a human-centered approach to innovation.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Design/Design-Thinking.jpeg?raw=true",
    originalPrice: "12480",
    discountedPrice: "4999",
    discount: "60",
    createdBy: "Designit Strategic Design, Alan Cooper",
    language: ["English", "Italian", "German"],
    duration: "1h 42m",
    noOfLectures: "55",
    rating: "3.8",
    categoryName: "Design",
  },
  {
    _id: uuid(),
    title: "The complete AutoCAD 2018-21 course",
    subTitle:
      "A complete course for learning AutoCAD from scratch to professional level.",
    description:
      "This course is a full-length AutoCAD 2018, 19, 20 and 2021 learning package which contains almost all of the topics that you will ever need to work with this software. The course is designed for a beginner as well as seasoned users. A beginner can start learning the software right from scratch by following the course along just from lecture one. A seasoned AutoCAD user will also find this course very comprehensive and they can choose the topics they want to learn about skipping the basics.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Design/autocad.jpg?raw=true",
    originalPrice: "4500",
    discountedPrice: "3150",
    discount: "30",
    createdBy: "Jaiprakash Pandey",
    language: ["English", "French", "German"],
    duration: "18h 15m",
    noOfLectures: "186",
    rating: "4.2",
    categoryName: "Design",
  },
  {
    _id: uuid(),
    title: "Machine Learning A-Z™: Hands-On Python & R In Data Science",
    subTitle:
      "Learn to create Machine Learning Algorithms in Python and R from two Data Science experts. Code templates included.",
    description:
      "Interested in the field of Machine Learning? Then this course is for you! This course has been designed by two professional Data Scientists so that we can share our knowledge and help you learn complex theory, algorithms, and coding libraries in a simple way. We will walk you step-by-step into the World of Machine Learning. With every tutorial, you will develop new skills and improve your understanding of this challenging yet lucrative sub-field of Data Science.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Development/machine-learning.jpg?raw=true",
    originalPrice: "3499",
    discountedPrice: "2620",
    discount: "25",
    createdBy: "Kirill Eremenko",
    language: ["English"],
    duration: "44h 29m",
    noOfLectures: "320",
    rating: "4.8",
    categoryName: "Development",
  },
  {
    _id: uuid(),
    title: "2022 Complete Python Bootcamp From Zero to Hero in Python",
    subTitle:
      "Learn Python like a Professional Start from the basics and go all the way to creating your own applications and games",
    description:
      "This course will teach you Python in a practical manner, with every lecture comes a full coding screencast and a corresponding code notebook! Learn in whatever manner is best for you! We will start by helping you get Python installed on your computer, regardless of your operating system, whether its Linux, MacOS, or Windows, we've got you covered.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Development/python.jpg?raw=true",
    originalPrice: "5500",
    discountedPrice: "2860",
    discount: "48",
    createdBy: "Jose Portillia",
    language: ["English", "French"],
    duration: "22h 13m",
    noOfLectures: "155",
    rating: "4.7",
    categoryName: "Development",
  },
  {
    _id: uuid(),
    title: "The Web Developer Bootcamp 2022",
    subTitle:
      "COMPLETELY REDONE - The only course you need to learn web development - HTML, CSS, JS, Node, and More!",
    description:
      " Welcome to the brand new version of The Web Developer Bootcamp, Udemy's most popular web development course.  This course was just completely overhauled to prepare students for the 2022 job market, with over 60 hours of brand new content. This is the only course you need to learn web development. There are a lot of options for online developer training, but this course is without a doubt the most comprehensive and effective on the market. ",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Development/web%20dev.jpg?raw=true",
    originalPrice: "4999",
    discountedPrice: "1749",
    discount: "65",
    createdBy: "Colt Steele",
    language: ["English", "German"],
    duration: "63h 47m",
    noOfLectures: "615",
    rating: "4.9",
    categoryName: "Development",
  },
  {
    _id: uuid(),
    title: "iOS & Swift - The Complete iOS App Development Bootcamp",
    subTitle:
      "From Beginner to iOS App Developer with Just One Course! Fully Updated with a Comprehensive Module Dedicated to SwiftUI!",
    description:
      "This Swift 5.1 course is based on our in-person app development bootcamp in London, where we've perfected the curriculum over 4 years of in-person teaching. Our complete app development bootcamp teaches you how to code using Swift 5.1 and build beautiful iOS 13 apps for iPhone and iPad. Even if you have ZERO programming experience. I'll take you step-by-step through engaging and fun video tutorials and teach you everything you need to know to succeed as an iOS app developer. The course includes 55+ hours of HD video tutorials and builds your programming knowledge while making real world apps. e.g. Pokemon Go, Whatsapp, QuizUp and Yahoo Weather.",
    img: "https://raw.githubusercontent.com/pankaj-prog/Ecom-images/main/Development/ios%20swift.webp",
    originalPrice: "3499",
    discountedPrice: "455",
    discount: "87",
    createdBy: "Dr. Angela Yu",
    language: ["English", "French", "German"],
    duration: "60h 25m",
    noOfLectures: "542",
    rating: "4.2",
    categoryName: "Development",
  },
  {
    _id: uuid(),
    title: "Master the Coding Interview: Data Structures + Algorithms",
    subTitle:
      "Ultimate coding interview bootcamp. Get more job offers, negotiate a raise: Everything you need to get the job you want!",
    description:
      "Want to land a job at a great tech company like Google, Microsoft, Facebook, Netflix, Amazon, or other companies but you are intimidated by the interview process and the coding questions? Do you find yourself feeling like you get 'stuck' every time you get asked a coding question? This course is your answer. Using the strategies, lessons, and exercises in this course, you will learn how to land offers from all sorts of companies. Many developers who are 'self taught', feel that one of the main disadvantages they face compared to college educated graduates in computer science is the fact that they don't have knowledge about algorithms, data structures and the notorious Big-O Notation. Get on the same level as someone with computer science degree by learning the fundamental building blocks of computer science which will give you a big boost during interviews. You will also get access to our private online chat community with thousands of developers online to help you get through the course.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Development/dsa%20and%20algorithms.png?raw=true",
    originalPrice: "5499",
    discountedPrice: "2900",
    discount: "47",
    createdBy: "Andrei Neagoie",
    language: ["English", "Italian"],
    duration: "19h 40m",
    noOfLectures: "261",
    rating: "4.5",
    categoryName: "Development",
  },
  {
    _id: uuid(),
    title: "Ultimate AWS Certified Solutions Architect Associate 2022",
    subTitle:
      "Full Practice Exam | Learn Cloud Computing | Pass the AWS Certified Solutions Architect Associate Certification SAA-C02!",
    description:
      "The AWS Certified Solutions Architect Associate certification is one of the most challenging exams. It's great at assessing how well you understand not just AWS, but making sure you are making the best architectural decisions based on situations, which makes this certification incredibly valuable to have and pass. Rest assured, I've passed it myself with a score of 982 out of 1000. Yes, you read that right, I only made one mistake! Next, I want to help YOU pass the AWS Certified Solutions Architect Associate certification with flying colors.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/IT%20&%20Security/aws.jpg?raw=true",
    originalPrice: "4500",
    discountedPrice: "1800",
    discount: "60",
    createdBy: "Stephane Maarek",
    language: ["English"],
    duration: "26h 54m",
    noOfLectures: "373",
    rating: "3.5",
    categoryName: "IT + Security",
  },
  {
    _id: uuid(),
    title: "The Complete Networking Fundamentals Course. Your CCNA start",
    subTitle:
      "Learn about networking and start your journey to Cisco 200-301 Certification.",
    description:
      "Welcome to the Complete Network Fundamentals Course! In this course, you will learn the technologies that keep the world as you know today connected and running. We cover both the fundamentals of networking as well as the topics in the new Cisco CCNA 200-301 exam. Networks are all around us and you are using one right now to access this course. ",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/IT%20&%20Security/basic-fundamental-of-networking.jpg?raw=true",
    originalPrice: "4999",
    discountedPrice: "2499",
    discount: "50",
    createdBy: "David Bombal",
    language: ["English", "French"],
    duration: "80h",
    noOfLectures: "685",
    rating: "4.2",
    categoryName: "IT + Security",
  },
  {
    _id: uuid(),
    title: "Learn Ethical Hacking From Scratch",
    subTitle:
      "Become an ethical hacker that can hack computer systems like black hat hackers and secure them like security experts.",
    description:
      "This course is highly practical but it won't neglect the theory; we'll start with ethical hacking basics, breakdown the different penetration testing fields and install the needed software (on Windows, Linux and Mac OS X), then we'll dive and start hacking straight away. You'll learn everything by example, by analysing and exploiting different systems such as networks, servers, clients, websites .....etc. We'll never have any boring dry theoretical lectures.",
    img: "https://raw.githubusercontent.com/pankaj-prog/Ecom-images/main/IT%20%26%20Security/ethical%20hacking.webp",
    originalPrice: "7499",
    discountedPrice: "4499",
    discount: "40",
    createdBy: "Zaid Sabih",
    language: ["English", "French", "German", "Italian"],
    duration: "15h 45m",
    noOfLectures: "145",
    rating: "4.8",
    categoryName: "IT + Security",
  },
  {
    _id: uuid(),
    title: "Learn Linux in 5 Days and Level Up Your Career",
    subTitle:
      "Use the in-demand Linux skills you learn in this course to get promoted or start a new career as a Linux professional.",
    description:
      "If you want to learn how to use Linux and level up your career but are pressed for time, read on. Hello. My name is Jason Cannon and I'm the author of Linux for Beginners as well as the founder of the Linux Training Academy. When I ask people to tell me what their biggest challenge is to learning Linux, they all say the same thing: Time. That's why I've created this course. Give me just 45 minutes a day for the next 5 days and I will teach you exactly what you need to know about the Linux operating system. You'll learn the most important concepts and commands, and I'll even guide you step-by-step through several practical and real-world examples. So, if you can spare a few minutes a day and want to learn the ins-and-outs of the Linux Operating System, join me and the other students in this course today.",
    img: "https://raw.githubusercontent.com/pankaj-prog/Ecom-images/main/IT%20%26%20Security/linux.avif",
    originalPrice: "5999",
    discountedPrice: "5099",
    discount: "15",
    createdBy: "Jason Cannon",
    language: ["English", "Italian"],
    duration: "13h 23m",
    noOfLectures: "83",
    rating: "4.2",
    categoryName: "IT + Security",
  },
  {
    _id: uuid(),
    title: "IT Help Desk Professional",
    subTitle:
      "Get Hands-On Experience on Helpdesk Skills, Learn, Master & Troubleshoot All What It Takes To Get You a Job",
    description:
      "Do you want to start your career in the IT world? Do you want to start building your IT career path from a solid ground? You are in the right place! Wondering why? Let’s see. Because when you want to become an IT specialist, you have to start from the basics, you need to master computers & everything related to that, how they work, how to install operating systems like Windows on machines, how they communicate, how to manage them, and of course troubleshooting all that, that's from a hardware point of view, while taking into consideration the need to learn how users are managed through network, how you can manage users accounts permissions, passwords, access, all through Active Directory.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/IT%20&%20Security/IT%20help.jpg?raw=true",
    originalPrice: "3499",
    discountedPrice: "455",
    discount: "87",
    createdBy: "Paul Hill, Omar Dabbas",
    language: ["English", "German"],
    duration: "1h 42m",
    noOfLectures: "20 ",
    rating: "3.5",
    categoryName: "IT + Security",
  },
  {
    _id: uuid(),
    title: "Instagram Marketing 2022: Complete Guide To Instagram Growth",
    subTitle:
      "Attract Hyper-Targeted Instagram Followers, Convert Followers to Paying Customers, & Expand your Brand Using Instagram",
    description:
      "This Instagram course is designed for anyone  who want to learn how to use Instagram to grow their followers and business. We are constantly keeping up with all of the new features and changes implemented and you have lifetime access to the course. In this course, we start with the very basics and you will learn how to create a powerful, professional Instagram profile for your business designed to effectively appeal your target customer. Even for people who have already established an account, it is imperative to know that you have done this in the optimal way for Instagram growth and marketing!",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Marketing/Instagram-Marketing.png?raw=true",
    originalPrice: "2500",
    discountedPrice: "1250",
    discount: "50",
    createdBy: "Benjamin Wilson",
    language: ["English"],
    duration: "7h 40m",
    noOfLectures: "65",
    rating: "4.5",
    categoryName: "Marketing",
  },
  {
    _id: uuid(),
    title: "The Complete Copywriting Course : Write to Sell Like a Pro",
    subTitle:
      "Write Effective Sales Copy & Grow Your Business & Career // Access Timeless Copywriting Formulas, Templates & FREE Tools",
    description:
      "This course is about fresh actionable lessons, delivered succinctly. (Just like good copy!) And it's about practical,  but fun copy missions and memorable formulas you can put to work -- even in your next email. In fact, I'm so confident you're gonna LOVE IT, if you don't agree, I offer a 100% MONEY BACK GUARANTEE within 30 days. So you've got nothing to lose, by having a sneaky peek, right? Okay, ready to get started? Pull up a chair, grab your laptop and let’s begin this exciting adventure together, today.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Marketing/copywriting.png?raw=true",
    originalPrice: "3499",
    discountedPrice: "2099",
    discount: "40",
    createdBy: "Tamsin Henderson",
    language: ["English", "French"],
    duration: "2h 58m",
    noOfLectures: "39",
    rating: "4.2",
    categoryName: "Marketing",
  },
  {
    _id: uuid(),
    title: "SEO 2022: Complete SEO Training + SEO for WordPress Websites",
    subTitle:
      "Competitor + Keyword Research, On Page + Technical SEO, Core Web Vitals, Pagespeed, Backlinks SEO & WordPress Training",
    description:
      "This Complete SEO 2022 training course is all about 50+ Search Engine Optimization factors on how to reach top spot on search engines like Google and Bing. This entire course is based on a keyword research compiled from 10,000 keywords for top 30 SERPs across the years 2014 to 2022. So they are all new, working and they apply 100% to 2022 and up. Also this is the most rated SEO course on the platform.",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Marketing/SEO.jpg?raw=true",
    originalPrice: "3499",
    discountedPrice: "455",
    discount: "87",
    createdBy: "Arun Nagarathanam",
    language: ["English", "German"],
    duration: "12h 6m",
    noOfLectures: "120",
    rating: "4.5",
    categoryName: "Marketing",
  },
  {
    _id: uuid(),
    title: "YouTube Masterclass - Your Complete Guide to YouTube",
    subTitle:
      "Complete guide to starting a YouTube channel, getting more views & subscribers, and building a brand with videos!",
    description:
      "This course is aimed at teaching new YouTubers what it takes to create great videos and make money from them. Most lessons are hands-on tutorials where we walk you through not only what it takes to succeed, but where we show you exactly how to do it. You'll start with the basics - the best practices for all YouTubers. These tips will get you in the mindset of a YouTuber. You'll learn how to use the YouTube platform. You’ll sign up for an account, get verified as a YouTube partner, and know how to navigate the Creator Studio",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Marketing/youtube.jpg?raw=true",
    originalPrice: "7500",
    discountedPrice: "3375",
    discount: "55",
    createdBy: "Phil Ebiner",
    language: ["English", "German", "Italian"],
    duration: "5h 35m",
    noOfLectures: "67",
    rating: "2.5",
    categoryName: "Marketing",
  },
  {
    _id: uuid(),
    title: "ClickBank Success – Affiliate Marketing Without A Website",
    subTitle:
      "Learn and model my proven system for success as a ClickBank affiliate. No hidden secrets - I reveal it all!",
    description:
      "'ClickBank Success – Affiliate Marketing Without A Website' is a practical course that will empower you with you a viable and easy-to-follow system to generate income online through promoting ClickBank products.You will discover how easy it is to get started by learning the core technique of Direct Linking through Search Engine Pay Per Click marketing – you don't need to have a website, domain, hosting, whatsoever. This technique is specially designed to help you take as little time as possible to get your first sales in ClickBank so that you can gain the confidence you need and build up your momentum from there!",
    img: "https://github.com/pankaj-prog/Ecom-images/blob/main/Marketing/click%20bank.jpg?raw=true",
    originalPrice: "4499",
    discountedPrice: "2699",
    discount: "40",
    createdBy: "KC Tan",
    language: ["English", "French"],
    duration: "3h 5m",
    noOfLectures: "65",
    rating: "3.8",
    categoryName: "Marketing",
  },
];
